### ISSUE TITLE
 error  in ./node_modules/zh-to-number/dist/index.mjs

### ISSUE THREAD

**Issue by CHONGE** [condorheroblog/number-zh#1]
error  in ./node_modules/zh-to-number/dist/index.mjs

Module parse failed: Unexpected token (95:37)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| function resolveOptions(options) {
>   const language = options.language ?? "zh-CN-lowercase";
|   if (!RESOURCES.hasOwnProperty(language)) {
|     throw new Error(`${language} does not appear in resources`);

 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/views/bid/dept/bidDept.vue?vue&type=script&lang=js 28:18-41
 @ ./src/views/bid/dept/bidDept.vue?vue&type=script&lang=js
 @ ./src/views/bid/dept/bidDept.vue
 @ ./src/views sync ^\.\/.*$
 @ ./src/store/modules/permission.js
 @ ./src/store/index.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://10.0.0.3:80&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by condorheroblog** [comment]
May be the Node version is too low. 

Try upgrading Node.
